= Intro

Setting up Re-core is pretty easy, most of the work is making sure you have VM templates that it can use, check link:re-pack.html[Re-pack] on how to do just that.

== Setup

Its easy to get going just clone the repo and launch the REPL:

```clojure
$ git clone git@github.com:re-ops/re-core.git
$ cd re-core
# Now start the REPL environment
$ lein repl
[re-core]λ: (go)
nil
```

Now head on to configuration and create VM templates.

== Templates

Re-core clones templates in order to create new VM instances, we use link:re-pack.html[Re-pack] to create our templates, which contain the minimal setup for required for Re-core to manage the instance:

* re-ops user for remote access management.
* authorized ssh-key (for automated access) under /home/re-ops/.ssh/authorized_keys
* Configuration management tools (like Puppet 4.x) etc..

Not all templates require the same setup so check the matching hypervisors section for more info.


== Configuration

The configuration holds the information on how to connect to different hypervisors, you can start by copying:

```bash
$ cp data/resources/re-core.edn ~/.re-core.edn
```

Any configuration change can be reflected immediately by:

```clojure
[re-core]λ: (reset)
```
The configuration file is divided to the following sections:

*   Re-core properties like: ports, log settings
*   Hypervisors like AWS, KVM and Digitalocean
*   Elasticsearch settings
*   SSH settings (key used to connect to remote instances)

The Re-core section (situated on top) contains the configuration options of the server itself:
```clojure
{
 :re-core {
   :port 8082
   :log {
     :level :info
     :path "re-core.log"
   }
 }

 :elasticsearch {
   :host "localhost"
   :port 9200
   :user "elastic"
   :pass "changeme"
   :index "re-core"
 }

 :ssh {
   :private-key-path "/home/foo/.ssh/id_rsa"
 }

}
```

[options="header"]
.Mandatory Settings
|===
|Section|Property|Description|Comments

.1+| ports
| port
| Standard http port
| Used for endpoint, used reverse proxy to secure

.2+| log
| level
| Default logging level
| Optional values include: trace, debug, info, error.

| path
| Where the log file is store locally
|

.5+| elasticsearch
| host
| The host Elasticsearch is running on
|

| port
| http API port (9200 by default)
|


| user
| Elasticsearch user name
|

| pass
| Elasticsearch password
|


| index
| The index name that re-core will use
|

.1+| ssh
| private-key-path
| Private ssh key path
| Used to perform remote tasks over ssh

|===

== Hypervisors

=== AWS

AWS configuration goes under the hypervisor/aws section in the link:re-core.html/_configuration[configuration] file:

```clojure
{
  :hypervisor {
   :dev {
     :aws {
       :access-key ""
       :secret-key ""
       :ostemplates {
         :ubuntu-16.04 {:ami "" :flavor :debian}
       }
       :default-vpc {
          :vpc-id "vpc-123456" :subnet-id "subnet-123456" :assign-public true
        }
      }
    }
  }
}
```

[options="header"]
.AWS configuration
|===
| Section | Property | Description | Comments

| access-key
|
| AWS access key
|

| secret-key
|
| AWS API secret key
|

| ostemplates
|
| Mappings between system os key to AMI and flavor (redhat or debian).
|

.3+| default-vpc
| vpc-id
| The id of the VPC that will be used with EC2 instances.
|

| subnet-id
| The id of the subnet that will be used with EC2 instances.
|

| assign-public
| Whether to assign a public IP or not.
| If false then a VPN is used to access the internal VPC network.

|===


=== Digitalocean

link:https://www.digitalocean.com/[Digitalocean] is supported with the following configuration:


```clojure
:hypervisor {
  :dev {
    :digital-ocean {
      :token ""
      :ssh-key ""
      :ostemplates {
         :ubuntu-16.04  {:image "ubuntu-16-04 :flavor :debian}
      }
     }
   }
}
```
.Digitalocean configuration

|===
|Section|Property|Description|Comments

| token
|
| Digitalocean authentication token
|

| ssh-key
| SSH key id in Digitalocean UI
| Used for password-less access to droplets.
|

| ostemplates
|
| Mapping from OS key to its Digitalocean image
| Check link:re-pack.html[Re-pack] on how to create a template

|===

=== KVM

link:http://www.linux-kvm.org/page/Main_Page[KVM] is supported with the following configuration:

```clojure
:hypervisor {
  :dev {
    :kvm  {
      :nodes {
         :remote {:username "ronen" :host "somehost" :port 22}
       }
      :ostemplates {
         :ubuntu-16.04 {:template "ubuntu-16.04" :flavor :debian}
      }
    }
  }
}
```

Note: we used libvirt over SSH (using key based auth).

.KVM configuration
|===
|Section|Property|Description|Comments

.3+| nodes
| username
| SSH user name
| Add your ssh key to /home/{user}/.ssh/authorized_keys

| host
| KVM node host
|

| port
| SSH port
|

.2+| ostemplates

| template
| Template VM name
| check link:re-pack.html#deploy[Deploy]

| flavor
| OS flavor of the template
| currently only :debian supported

|===

==== KVM Libvirt

Re-core uses link:https://libvirt.org/[libvirt] in order to access KVM hypervisor instances.

Libvirt uses SSH (with SSH keys) in order to access remote hypervisors, this requires us to ssh-copy-id from the Re-core host into KVM hosts we would like to manage:

```bash
$ ssh-copy-id user@remote-kvm

```

Note: deploying Re-core within as a VM that we would like to manage isn't possible due to link:https://wiki.libvirt.org/page/TroubleshootMacvtapHostFail[networking limitations] imposed by KVM (install Re-core outside any of the managed VMs).

When using Re-core and KVM locally (same host) we must set the node key as localhost so Re-core KVM provider will use hosts NAT addresses and not bridge interface:

```clojure
    :kvm  {
        :nodes {
           :localhost {
              ...
           }
         }
     }
```



=== Support Matrix

Currently supported and verified systems that Re-core works with:

.Supported hypervisors
|===
|Name|Versions|Operating systems|Comments
| AWS
|
| Ubuntu > = 16.x
|

| Digitalocean
|
| Ubuntu > = 16.x
|

| KVM
|
| Ubuntu > = 16.04
|
|===


Note: more OS and hypervisor support will be added in the future.

